import ToasterProvider from "@/components/providers/ToasterProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { auth } from "@/lib/auth";
import AuthenticationPage from "@/components/AuthClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        {session ? children : <AuthenticationPage />}
      </body>
    </html>
  );
}
